<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    FOS\UserBundle\FOSUserBundle::class => ['all' => true],
    FOS\RestBundle\FOSRestBundle::class => ['all' => true],
    Nelmio\CorsBundle\NelmioCorsBundle::class => ['all' => true],
    ApiPlatform\Symfony\Bundle\ApiPlatformBundle::class => ['all' => true],
    SpriteGenerator\SpriteGeneratorBundle::class => ['all' => true],
    Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
    PartKeepr\DoctrineReflectionBundle\PartKeeprDoctrineReflectionBundle::class => ['all' => true],
    PartKeepr\RESTBundle\PartKeeprRESTBundle::class => ['all' => true],
    PartKeepr\SetupBundle\PartKeeprSetupBundle::class => ['all' => true],
    PartKeepr\CronLoggerBundle\PartKeeprCronLoggerBundle::class => ['all' => true],
    PartKeepr\CategoryBundle\PartKeeprCategoryBundle::class => ['all' => true],
    PartKeepr\UploadedFileBundle\PartKeeprUploadedFileBundle::class => ['all' => true],
    PartKeepr\FrontendBundle\PartKeeprFrontendBundle::class => ['all' => true],
    PartKeepr\SiPrefixBundle\PartKeeprSiPrefixBundle::class => ['all' => true],
    PartKeepr\AuthBundle\PartKeeprAuthBundle::class => ['all' => true],
    PartKeepr\CoreBundle\PartKeeprCoreBundle::class => ['all' => true],
    PartKeepr\MimetypeIconsBundle\PartKeeprMimetypeIconsBundle::class => ['all' => true],
    PartKeepr\FootprintBundle\PartKeeprFootprintBundle::class => ['all' => true],
    PartKeepr\UnitBundle\PartKeeprUnitBundle::class => ['all' => true],
    PartKeepr\PartBundle\PartKeeprPartBundle::class => ['all' => true],
    PartKeepr\StockBundle\PartKeeprStockBundle::class => ['all' => true],
    PartKeepr\DistributorBundle\PartKeeprDistributorBundle::class => ['all' => true],
    PartKeepr\ManufacturerBundle\PartKeeprManufacturerBundle::class => ['all' => true],
    PartKeepr\ImageBundle\PartKeeprImageBundle::class => ['all' => true],
    PartKeepr\ProjectBundle\PartKeeprProjectBundle::class => ['all' => true],
    PartKeepr\TipOfTheDayBundle\PartKeeprTipOfTheDayBundle::class => ['all' => true],
    PartKeepr\ExportBundle\PartKeeprExportBundle::class => ['all' => true],
    PartKeepr\StatisticBundle\PartKeeprStatisticBundle::class => ['all' => true],
    PartKeepr\SystemPreferenceBundle\PartKeeprSystemPreferenceBundle::class => ['all' => true],
    PartKeepr\ImportBundle\PartKeeprImportBundle::class => ['all' => true],
    PartKeepr\BatchJobBundle\PartKeeprBatchJobBundle::class => ['all' => true],
    PartKeepr\OctoPartBundle\PartKeeprOctoPartBundle::class => ['all' => true],
    PartKeepr\MobileFrontendBundle\PartKeeprMobileFrontendBundle::class => ['all' => true],
    Knp\Bundle\GaufretteBundle\KnpGaufretteBundle::class => ['all' => true],
];
