fos_user:
    db_driver: orm
    firewall_name: main
    user_class: PartKeepr\AuthBundle\Entity\FOSUser
    from_email:
        address: "nobody@nobody.com"
        sender_name: "nobody"
    service:
        mailer: fos_user.mailer.twig_swift
