framework:
    #esi:             ~
    translator:      { fallback: en }
    serializer:      { enable_annotations: true }
    secret:          '%secret%'
    router:
        resource: "%kernel.project_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: true }
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true
    error_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
