# Doctrine Configuration
doctrine:
    dbal:
        driver:   '%database_driver%'
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8
        server_version: 5.6

        # if using pdo_sqlite as your database driver, add the path in parameters.php
        # e.g. database_path: %kernel.project_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        connection: ~
        auto_mapping: true
#        metadata_cache_driver: '%cache.doctrine%'
#        query_cache_driver: '%cache.doctrine%'
#        result_cache_driver: '%cache.doctrine%'
        mappings:
          gedmo_tree:
            type: annotation
            prefix: Gedmo\Tree\Entity
            dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Entity"
            alias: GedmoTree # this one is optional and will default to the name set for the mapping
            is_bundle: false

doctrine_migrations:
    migrations_paths:
        PartKeepr\CoreBundle\DoctrineMigrations: '%kernel.project_dir%/src/PartKeepr/CoreBundle/DoctrineMigrations'
    storage:
        # Default (SQL table) metadata storage configuration
        table_storage:
            table_name: SchemaVersions

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: true
