partkeepr:
  image_cache_directory: '%kernel.cache_dir%/imagecache/'
  cronjob_check: '%partkeepr.cronjob.check%'
  authentication_provider: '%authentication_provider%'
  directories:
    iclogo: '%kernel.project_dir%/../data/images/iclogo/'
    temp: '%kernel.project_dir%/../data/temp/'
    tempfile: '%kernel.project_dir%/../data/files/Temporary/'
    footprintattachment: '%kernel.project_dir%/../data/files/FootprintAttachment/'
    footprint: '%kernel.project_dir%/../data/images/footprint/'
    partattachment: '%kernel.project_dir%/../data/files/PartAttachment/'
    storagelocation: '%kernel.project_dir%/../data/images/storagelocation/'
    mimetype_icons: '%kernel.project_dir%/../src/PartKeepr/MimetypeIconsBundle/Resources/public/images/mimes/'
    projectattachment: '%kernel.project_dir%/../data/files/ProjectAttachment/'
